### ISSUE TITLE
Closer match of OpenFV formatting examples

### ISSUE THREAD

**Issue by alerque** [source-foundry/font-v#117]
Docs (see Readme and #19) suggests the goal here is to follow OpenFV, but in all the [OpenFV examples](https://github.com/openfv/openfv#examples) there is a space between segments (i.e. `Version 0.000; [shortsha]` not `Version 0.000;[shortsha]`). Which end gives here, what should be the defaco normalization?

**Comment by chrissimpkins** [comment]
It sounds like we should resolve the discussion about whether to use SHA at all. I would consider OpenFV to be a very immature proposal.  It hasn't received much feedback.  Perhaps we should have a look through that proposal and revise so that it works for reproducible builds, then return here to implement it.  Granted what you point out is an inconsistency.  I can fix it but we may as well make the spec adequate before we work on the implementation details.

**Comment by chrissimpkins** [comment]
As of the v2.0.0 release, I am abandoning the OpenFV spec in this tool / library altogether.  The de facto specification will be as specified in the sources here.  Please weigh in if you prefer a format that is not currently the default.  I'll close this issue as unnecessary as all OpenFV spec links in the project repository documentation and source documentation have been removed.
